adding riemann-mongodb

diff --git a/jobs/riemann-mongodb/templates/ctl-mongodb.erb b/jobs/riemann-mongodb/templates/ctl-mongodb.erb
--- a/jobs/riemann-mongodb/templates/ctl-mongodb.erb
+++ b/jobs/riemann-mongodb/templates/ctl-mongodb.erb
@@ -1,9 +1,12 @@
 #!/bin/bash
 
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
 RUN_DIR=/var/vcap/sys/run/riemann-mongodb
 LOG_DIR=/var/vcap/sys/log/riemann-mongodb
 JOB_DIR=/var/vcap/jobs/riemann-mongodb
-RIEMANN_PIDFILE=${RUN_DIR}/mongodb_server_pid
+PIDFILE=${RUN_DIR}/mongodb_server_pid
 
 case $1 in
 
@@ -11,21 +14,21 @@ case $1 in
     mkdir -p $RUN_DIR $LOG_DIR
     chown -R vcap:vcap $RUN_DIR $LOG_DIR
 
-    cd /var/vcap/packages/riemann-mongodb/
+    cd /var/vcap/packages/riemann-mongodb/riemann-mongodb
 
     export PATH=/var/vcap/packages/ruby/bin:$PATH
 
-    bundle exec riemann-mongodb --host <%= properties.riemann.server %> --event-host <%= spec.index %>.<%= spec.job.name %>.<%= properties.riemann.suffix %> \
-        >> $LOG_DIR/riemann-mongodb.stdout.log \
-        >> $LOG_DIR/riemann-mongodb.stderr.log &
-    echo $! > $RIEMANN_PIDFILE
+    bundle exec riemann-mongodb --host <%= properties.riemann.server %> --event-host <%= spec.job.name %>.<%= spec.index %>.<%= properties.riemann.suffix %> \
+        1>> $LOG_DIR/riemann-mongodb.stdout.log \
+        2>> $LOG_DIR/riemann-mongodb.stderr.log &
+    echo $! > $PIDFILE
 
     ;;
 
   stop)
 
-    kill -9 `cat $RIEMANN_PIDFILE`
-    rm -f $RIEMANN_PIDFILE
+    kill -9 `cat $PIDFILE`
+    rm -f $PIDFILE
     ;;
 
   *)
